name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    strategy:
      matrix:
        node-version: [18]
        pnpm-version: [9]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm ${{matrix.pnpm-version}}
        uses: pnpm/action-setup@v3
        with:
          version: ${{matrix.pnpm-version}}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm build --preset cloudflare_pages
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=experiments
